services:
  hae-server:
    container_name: health-auto-export-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATA_DIR=/data
      - READ_TOKEN=${READ_TOKEN}
      - WRITE_TOKEN=${WRITE_TOKEN}
    volumes:
      - ./data:/data
    restart: unless-stopped
